services:
  symfony:
    build:
      target: prod
    volumes: []
    environment:
      APP_ENV: prod
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET_KEY_BASE64: ${JWT_SECRET_KEY_BASE64}
      JWT_PUBLIC_KEY_BASE64: ${JWT_PUBLIC_KEY_BASE64}
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}

  nginx:
    ports:
      - "80:80"
