game:
    resource:
        path: ../src/Game/
        namespace: App\Game
    type: attribute

entry:
    resource:
        path: ../src/Entry/
        namespace: App\Entry
    type: attribute

player:
    resource:
        path: ../src/Player/
        namespace: App\Player
    type: attribute

# config/routes.yaml
api_login_check:
    path: /api/login_check